### ISSUE TITLE
DEBUG enviroment variable not found

### ISSUE THREAD

**Issue by Madis0** [RozeFound/mmc-export#11]
The script does not know what to do with a resource pack (in resourcepacks folder of MMC pack).

Using python 3.10.4, pip 22.1, mmc-export 2.1.6

```
PS C:\Users\Madis> mmc-export -i "C:\Users\Madis\Desktop\Fabulously Optimized 3.8.1.zip" -f Modrinth -o modpacks
No config entry found for resource: Mod Menu Helper
Traceback (most recent call last):
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\Scripts\mmc-export.exe\__main__.py", line 7, in <module>
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\lib\site-packages\mmc_export\main.py", line 77, in main
    loop.run_until_complete(run())
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\lib\site-packages\mmc_export\main.py", line 61, in run
    project = "mmc-export" if os.environ['DEBUG'] != "TRUE" else "mmc_export"
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\lib\os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'DEBUG'
```

When removing the resourcepacks folder from the pack, I got a different, non-descriptive error:

```
Traceback (most recent call last):
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\Scripts\mmc-export.exe\__main__.py", line 7, in <module>
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\lib\site-packages\mmc_export\main.py", line 77, in main
    loop.run_until_complete(run())
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\lib\site-packages\mmc_export\main.py", line 61, in run
    project = "mmc-export" if os.environ['DEBUG'] != "TRUE" else "mmc_export"
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\lib\os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'DEBUG'
```

The same error occurred when I tried to import the pack to MMC, skip the folder when exporting and import to this tool again.

**Comment by Madis0** [comment]
I updated with `pip install mmc-export --upgrade` and now I'm getting a similar error:

```
PS C:\Users\Madis> mmc-export -i "C:\Users\Madis\Desktop\Fabulously Optimized 3.8.1.zip" -f Modrinth -o modpacks
No config entry found for resource: Mod Menu Helper
Traceback (most recent call last):
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\Scripts\mmc-export.exe\__main__.py", line 7, in <module>
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\lib\site-packages\mmc_export\main.py", line 77, in main
    loop.run_until_complete(run())
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\lib\site-packages\mmc_export\main.py", line 62, in run
    module = import_module(f".Formats.{format.lower()}", project)
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mmc-export'
```

**Comment by RozeFound** [comment]
Oh that's why

**Comment by RozeFound** [comment]
Must work now [6df6e8d](https://github.com/RozeFound/mmc-export/commit/6df6e8d78ce00c614f8192f8bb8de17edf542ab7)

**Comment by RozeFound** [comment]
Maybe I need to test it outside of dev enviroment more often

**Comment by Madis0** [comment]
Well, it still said "No config entry found for resource: Mod Menu Helper" which is confusing, but it successfully exported the ZIP.

**Comment by RozeFound** [comment]
This message means that it was not found anywhere and you didn't provided any config to resolve this.
Maybe I need to change the message, or add something like 'ignore' tag....
