### ISSUE TITLE
Overwrite the file when it exists

### ISSUE THREAD

**Issue by Madis0** [RozeFound/mmc-export#42]
We talked about this and you said it was a Windows limit of some Python command. 

Still, it needs fixing:

```
Traceback (most recent call last):
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\Scripts\mmc-export.exe\__main__.py", line 7, in <module>
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\lib\site-packages\mmc_export\main.py", line 59, in main
    loop.run_until_complete(run())
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\lib\site-packages\mmc_export\main.py", line 47, in run
    writer.write()
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\lib\site-packages\mmc_export\Formats\modrinth.py", line 113, in write
    archive.replace(archive.with_suffix(".mrpack"))
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 1245, in replace
    self._accessor.replace(self, target)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\Madis\\Desktop\\MR_Fabulously Optimized.zip' -> 'C:\\Users\\Madis\\Desktop\\MR_Fabulously Optimized.mrpack'`
```

**Comment by Madis0** [comment]
Nevermind, I had the zip opened and 7zip locked it.
