### ISSUE TITLE
string indices must be integers

### ISSUE THREAD

**Issue by Madis0** [RozeFound/mmc-export#50]
Running
`mmc-export -i "c:/Users/Madis/Desktop/Fabulously Optimized 3.9.0.zip" -f Modrinth --modrinth-search loose -o "c:/Users/Madis/Desktop/" -c "C:/Users/Madis/Documents/GitHub/fabulously-optimized/Modrinth/mmc-export.toml" -v 3.9.0`
on mmc-export 2.3.5

```
Traceback (most recent call last):
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\lib\site-packages\tenacity\_asyncio.py", line 51, in __call__
    result = await fn(*args, **kwargs)
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\lib\site-packages\mmc_export\Helpers\resourceAPI.py", line 196, in _get_batched_modrinth
    versions = {v[1]['files'][0]['hashes']["sha1"]: v[1] for v in await response.json()}
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\lib\site-packages\mmc_export\Helpers\resourceAPI.py", line 196, in <dictcomp>
    versions = {v[1]['files'][0]['hashes']["sha1"]: v[1] for v in await response.json()}
TypeError: string indices must be integers

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\Scripts\mmc-export.exe\__main__.py", line 7, in <module>
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\lib\site-packages\mmc_export\main.py", line 70, in main
    loop.run_until_complete(run())
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\lib\site-packages\mmc_export\main.py", line 42, in run
    intermediate = await parser.parse()
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\lib\site-packages\mmc_export\parser.py", line 78, in parse
    self.intermediate.resources = await self.resourceAPI.gather()
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\lib\site-packages\mmc_export\Helpers\resourceAPI.py", line 147, in gather
    await asyncio.gather(*futures)
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\lib\site-packages\tenacity\_asyncio.py", line 86, in async_wrapped
    return await fn(*args, **kwargs)
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\lib\site-packages\tenacity\_asyncio.py", line 48, in __call__
    do = self.iter(retry_state=retry_state)
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\lib\site-packages\tenacity\__init__.py", line 361, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x2479c4b1d20 state=finished raised TypeError>]
```

**Comment by RozeFound** [comment]
Oh, seems like modrinth API for batched requests finally fixed
