### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Madis0** [RozeFound/mmc-export#52]
```
Traceback (most recent call last):
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\lib\site-packages\mmc_export\Helpers\resourceAPI.py", line 201, in _get_batched_modrinth
    file = next(file for file in version['files']
StopIteration

The above exception was the direct cause of the following exception:     

Traceback (most recent call last):
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\lib\site-packages\tenacity\_asyncio.py", line 51, in __call__
    result = await fn(*args, **kwargs)
RuntimeError: coroutine raised StopIteration

The above exception was the direct cause of the following exception:     

Traceback (most recent call last):
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\Scripts\mmc-export.exe\__main__.py", line 7, in <module>
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\lib\site-packages\mmc_export\main.py", line 70, in main
    loop.run_until_complete(run())
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\lib\site-packages\mmc_export\main.py", line 42, in run
    intermediate = await parser.parse()
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\lib\site-packages\mmc_export\parser.py", line 78, in parse
    self.intermediate.resources = await self.resourceAPI.gather()        
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\lib\site-packages\mmc_export\Helpers\resourceAPI.py", line 147, in gather
    await asyncio.gather(*futures)
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\lib\site-packages\tenacity\_asyncio.py", line 86, in async_wrapped
    do = self.iter(retry_state=retry_state)
  File "C:\Users\Madis\AppData\Local\Programs\Python\Python310\lib\site-packages\tenacity\__init__.py", line 361, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x1ffcaf84370 state=finished raised RuntimeError>]
```

**Comment by Madis0** [comment]
Fixed in 2.3.10 already
